### ISSUE TITLE
Version 2.6.0: overflow size calculation crashes on non-string record values (NoMethodError: bytesize)

### ISSUE THREAD

**Issue by Perry45** [fluent-plugins-nursery/fluent-plugin-concat#134]
### Describe the bug

Since upgrading from fluent-plugin-concat 2.5.0 to 2.6.0, we are encountering runtime exceptions when processing logs.

The issue appears to be caused by the newly introduced overflow handling logic (e.g. buffer_limit_size, buffer_overflow_method), specifically in the size calculation of records.

In version 2.6.0, the plugin calculates record size using:
record.keys.sum(&:bytesize) + record.values.sum(&:bytesize)

This assumes that all keys and values are strings. However, in real-world usage (especially with structured JSON logs), record values can include:
Integer
Float
Boolean
Hash
Array
nil

Calling .bytesize on these types raises:

NoMethodError: undefined method `bytesize' for Integer (or other types)

### To Reproduce
```
{"message":"m","logtag":"F","count":1}
```

Minimal config:

```
<filter **>
  @type concat
  key message
  partial_key logtag
  partial_value P
</filter>
```

This results in:

NoMethodError: undefined method `bytesize' for Integer

### Expected behavior

The plugin should handle non-string values gracefully and not raise exceptions when calculating record size.

### Your Environment

```markdown
Logging operator: 6.4
fluent-plugin-concat: 2.6.0
```

### Your Configuration

```apache
-
```

### Your Error Log

```shell
2026-03-25 09:32:16 +0000 [warn]: #0 fluent/log.rb:393:: send an error event to @ERROR: error_class=NoMethodError error="undefined method 'bytesize' for an instance of Hash" location="/usr/local/bundle/gems/fluent-plugin-concat-2.6.0/lib/fluent/plugin/filter_concat.rb:406:in 'Array#sum'" tag="kubernetes.var.log.containers.webapp
```
